### ISSUE TITLE
Less smooth turning on\off

### ISSUE THREAD

**Issue by VladNord** [hencou/esphome-milight#10]
Thanks again for the great project.
Is it possible to make turning off\on process less smooth, like in Sidoh Milight hub?
Despite the fact that transition is 0 sec, turning on or off takes up to 3 seconds, with milight hub with same transmitter it takes less than second.
If needed, I can upload video.

I use nodemcu-32s with default VSPI pins.
Here is config for light, mi platform configured by default.

```
light:
- platform: mi                                                    
  name: LR                 
  device_id: 0xB                       
  group_id: 2                             
  remote_type: cct                    
  default_transition_length: 0s 
```
