### ISSUE TITLE
AZ Delivery D1 R32 sending issues

### ISSUE THREAD

**Issue by poudenes** [hencou/esphome-milight#3]
EDIT 7-12-2022: Removed part of config to make things readable

Hi There,

I receive information from my old Wemos D1 Milight Hub. The lights that are integrated in Home Assistant are acting on those data information. But when I want turn on or off with new board nothing happen.

```
#########################################################
# Below all fixed settings for Milight PCB
#########################################################
substitutions:
  devicename: milight-hub-test
  friendly: Milight Hub
  ip: 192.168.100.210
#########################################################

esphome:
  name: ${devicename}
  libraries:
    - milight=https://github.com/hencou/esphome-milight

external_components:
- source: github://hencou/esphome_components
  components: mi

esp32:
  board: az-delivery-devkit-v4 # 
  framework:
    type: arduino
  # restore_from_flash: true

api:
  encryption:
    key: !secret api_key

# time:
#   - platform: homeassistant
#     id: homeassistant_time

# preferences:
#   flash_write_interval: 1min
  
logger:
  
ota:
  safe_mode: true
  password: !secret password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  manual_ip:
    static_ip: ${ip}
    gateway: 192.168.100.1
    subnet: 255.255.255.0
    dns1: 192.168.100.1

  # ap:
  #   ssid: ${devicename}
  #   password: !secret password
  #   channel: 4

button:
  - platform: factory_reset
    name: "${friendly} - reset"

sensor:
  - platform: wifi_signal
    name: "${friendly} - wifi Signal"
    update_interval: 5min

  - platform: uptime
    name: "${friendly} - Uptime"
    update_interval: 5min
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly} - ip"
      icon: mdi:lan
    ssid:
      name: "${friendly} - ssid"
      icon: mdi:lan
    bssid:
      name: "${friendly} - bssid"
      icon: mdi:lan
    mac_address:
      name: "${friendly} - mac"
      icon: mdi:lan

  - platform: version
    name: "${friendly} - Version"
    hide_timestamp: true

#########################################################
# Below specific for Milight settings
#########################################################
mi:
  #########################################################
  # Wifi
  #########################################################
  listen_repeats: 2
  #########################################################
  # Setup
  #########################################################
  ce_pin: 21 # 13
  csn_pin: 22 # 5
  reset_pin: 16
  state_flush_interval: 0
  #########################################################
  # Radio
  #########################################################
  packet_repeats: 60 # 50
  packet_repeats_per_loop: 60 # 50
  radio_interface_type: nrf24
  rf24_power_level: MAX
  rf24_listen_channel: LOW
  rf24_channels:
    - LOW
    - MID
    - HIGH
  packet_repeat_throttle_threshold: 10000 # 10000
  packet_repeat_throttle_sensitivity: 5 # 5
  packet_repeat_minimum: 8 # 5
  enable_automatic_mode_switching: false  
  on_command_received:
    - homeassistant.event:
        event: esphome.mi_command_received
        data:
          device_id: !lambda 'return format_hex(data.device_id);'
          group_id: !lambda 'return data.group_id;'
          remote_type: !lambda 'return data.remote_type.c_str();'
          command: !lambda 'return data.command.c_str();'
#########################################################
# END
#########################################################

light:
#########################################################
# Dressoir
#########################################################
  - platform: mi
    id: dressoir_all
    name: "Dressoir all test"
    device_id: 0xAAAF
    group_id: 0
    remote_type: rgb_cct
    default_transition_length: 0s
```
