### ISSUE TITLE
(Feature request) When group 0 is used, update group 1,2,3 and 4

### ISSUE THREAD

**Issue by poudenes** [hencou/esphome-milight#6]
Hi All,

With Sidoh build I created in HA a automation to update group 1,2,3 and 4 when group 0 is used.
All bulbs individual have same settings at that moment. Now with ESPHome build and use Group 0 then individual settings of group 1,2,3 and 4 keeps their old settings.

In past this was a big issue when Milight disconnected and bulbs had state ON with Brightness 100%. In middle of night suddenly bulbs went on because of reconnection of the Milight ESP.

**Comment by hencou** [comment]
Hi Peter,

In the ESPHome group 0 is not supported, because it's not needed. Simply make a group of lights in HomeAssistant when you want to switch multiple lights at once.

**Comment by poudenes** [comment]
Oh. I have many group 0 in the config and they all working...

**Comment by shbatm** [comment]
I would like to see the group 0 working as well to update the others. The issue with using the light group in HA is it requires multiple transmissions to control the lights as opposed to a single command for Group 0 (similar issue to Zigbee and Insteon groups).

**Comment by poudenes** [comment]
I don't understand. I have 6 groups 0 in my config and they working. 

I do tests now for best settings with repeat values.
Turn on group 0 and then each single bulb a color.

Then discovered a repeat of the action. Hencou told me that's correct. Now I go folk the code and remove 1 line.

Test again if the repeat of commands is gone...

What I wanna say that group 0 was working all the time for me....

**Comment by poudenes** [comment]
To make it more clear 

I have add all bulbs that I want torn on or off of whatever in group 0

Group 1: bulb 1 paired
Group 2: bulb 2 and 3 paired
Group 3: bulb 4 and 5 paired

Group 0: bulb 1,2,3,4 and 5 paired

**Comment by hencou** [comment]
Hi,

I just tested with a group 0 config in the yaml but nothing happens with my bulbs then. How do you guys configure this in ESPHome and HomeAssistant? Do you have a light configured with group 0 and besides that the lights for the 1-4 (or 8) indiviual lights? How will HomeAssistant show the actual status of the light with group 0 then?

**Comment by shbatm** [comment]
Here's an example for me:

I have 2 sets of Driveway Landscape lights (Group 1 and Group 2) and also have a Group 0 defined that will control them all as one.

```yaml
  - platform: mi
    default_transition_length: 0s
    name: "Driveway Landscaping"
    remote_type: "rgb_cct"
    device_id: 0x5EC
    group_id: 0
  - platform: mi
    default_transition_length: 0s
    name: "Landscape Driveway 1"
    remote_type: "rgb_cct"
    device_id: 0x5EC
    group_id: 1
  - platform: mi
    default_transition_length: 0s
    name: "Landscape Driveway 2"
    remote_type: "rgb_cct"
    device_id: 0x5EC
    group_id: 2
```

So I can control all three switches in HA fine, Group 0, 1, or 2, however, when I control Group 0, the state doesn’t change for Group 1 and 2 to match, which is my interpretation of this issue.
