### ISSUE TITLE
Not fully function in HA

### ISSUE THREAD

**Issue by poudenes** [hencou/esphome-milight#8]
Hi All,

I removed the ESPhome config fully. Rebuild it again with all new updates in code.
I see some strange behaviors using HA commands.

1) turn on a bulb with a effect doesn't work sometimes. (im not clear when and when not)
2) using develop tool to turn on or off the bulb will work sometimes same as point 1
3) what always work is when you turn on a bulb with a kelvin state (color_temp) this will bring back the bulb back to life.
4) Then it's possible to turn on the bulb with an effect. Now it's working normal.

Sometimes I see this message in ESPhome log:

`[09:12:02][I][light:392]: 'Bedroom 6 esphome' - Keeping current color mode Color temperature for call without color mode.`

When Milight Hub (sidoh) below automation work perfectly:

```
- id: "44058c82-1994-4480-b883-47f9e00625ed"
  alias: "Scene - Sleeping"
  trigger:
    - platform: state
      entity_id: input_boolean.scene_sleeping
      to: "on"

  action:
    - service: light.turn_on
      target:
        entity_id: light.bedroom_all_esphome
      data:
        brightness_pct: 1
        transition: "25"

    - delay: "00:00:20"  # this will change because ESP is much accurate in time

    - service: light.turn_off
      target:
        entity_id: light.bedroom_all_esphome

    - service: light.turn_on
      target:
        entity_id: light.bedroom_5_esphome
      data:
        brightness_pct: 1
        effect: 0

    - delay:
        milliseconds: 300

    - service: light.turn_on
      target:
        entity_id: light.bedroom_6_esphome
      data:
        brightness_pct: 1
        effect: 0

    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.scene_sleeping

    - delay: "00:01:00"

    - service: light.turn_off
      target:
        entity_id: ['light.bedroom_5_esphome','light.bedroom_6_esphome','light.bedroom_all_esphome']

```
Here log of ESPhome that belong to automation above:
```
[09:23:33][D][light:035]: 'Bedroom all esphome' Setting: # MANUAL TURN ON 
[09:23:33][D][light:046]:   State: ON
[09:23:33][D][light:050]:   Brightness: 100%
[09:23:33][D][light:065]:   Color temperature: 283.0 mireds
[09:23:34][D][light:035]: 'Bedroom all esphome' Setting: # START OF AUTOMATION 
[09:23:34][D][light:050]:   Brightness: 1%
[09:23:34][D][light:084]:   Transition length: 5.0s
[09:23:40][D][light:035]: 'Bedroom all esphome' Setting:
[09:23:40][D][light:046]:   State: OFF
[09:23:41][D][light:035]: 'Bedroom 5 esphome' Setting:
[09:23:41][D][light:046]:   State: ON
[09:23:41][D][light:108]:   Effect: '0'
[09:23:41][D][light:035]: 'Bedroom 6 esphome' Setting:
[09:23:41][D][light:046]:   State: ON
[09:23:41][D][light:108]:   Effect: '0'
```
The 2 last bulbs not go on and there is no effect.

**Comment by poudenes** [comment]
There is some instability with effect option. 

This gives a lot of trouble
```
    - service: light.turn_on
      target:
        entity_id: light.bedroom_6_esphome
      data:
        brightness_pct: 1
        effect: 0
```

This gives less trouble
```
    - service: light.turn_on
      target:
        entity_id: light.bedroom_6_esphome

    - service: light.turn_on
      target:
        entity_id: light.bedroom_6_esphome
      data:
        brightness_pct: 1
        effect: 0
```

Both still have issues when select effect. Sometimes the bulb jumps to 'night_mode' and then you need turn off the bulb otherwise you can't change it to an effect. Only what work is select effect 'none' and then you can control the bulb again

**Comment by poudenes** [comment]
HI,

Did some more tests:

With Sidoh image I can change from all effect modes to an other. Even from `night_mode` to a effect from 0 to 8

With yours I can't change from `night_mode` to an other effect. 

Maybe something in code is not correct? 

All effect from 0 to 8 have same effect as Sidoh image. So the effects itself are ok

Also `white_mode` is missing in effect list

**Comment by poudenes** [comment]
For now found a workaround that seems to work:
```
    - service: light.turn_on
      target:
        entity_id: light.bedroom_esphome

    - service: light.turn_on
      target:
        entity_id: light.bedroom_esphome
      data:
        effect: 0
```
First turn on the bulb and then turn on with effect

tried it almost 15 times without issues now
